services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_SOCKET_URL=${VITE_SOCKET_URL_DOCKER:-http://localhost:3001}
    container_name: ai-theme-builder-frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_SOCKET_URL=${VITE_SOCKET_URL_DOCKER:-http://localhost:3001}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: ai-theme-builder-backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN_DOCKER:-http://localhost}
